FROM muslcc/x86_64:x86_64-linux-musl
LABEL maintainer="Andrew Dunham <andrew@du.nham.ca>"

# Install build dependencies
RUN apk add --no-cache \
    bash \
    curl \
    git \
    make \
    python3 \
    perl \
    linux-headers \
    autoconf \
    automake \
    libtool

# Add our build script and dependencies
COPY build-x86_64.sh /build/build.sh
COPY deps/ /build/deps/
RUN chmod +x /build/build.sh

# This builds the program and copies it to /output
CMD ["/bin/bash", "/build/build.sh"]